[package]
name = "iana-ip-db"
version = "0.1.0"
authors = ["luozijun <luozijun.assistant@gmail.com>"]
edition = "2018"
exclude = [
    "data/",
]

[workspace]
members = [
    "sync",
    "parse",
]

[features]
default = [ ]